### ISSUE TITLE
can't use mouse click to input

### ISSUE THREAD

**Issue by gary5034** [antest1/GotoBrowser#105]
When my mouse connect to cell phone and my tablet, the click function is not working in game.

In game, the scroll function works fine. Just the click function is not working even at the game start screen.

Click function was fine at 2.13rev3 and previous version.

**Comment by laplamgor** [comment]
What is your current version

**Comment by gary5034** [comment]
It's the latest 2.13rev5

**Comment by laplamgor** [comment]
oh. it should be fixed in https://github.com/antest1/GotoBrowser/pull/103 but it has not been released yet. I guess there are too little change for a new version

**Comment by antest1** [comment]
I think I'll make release for gotobrowser this week, thank you for your patience.

**Comment by antest1** [comment]
so unfortunately seems #103 does not solve the issue: https://x.com/akiel_chemko/status/1896502149372358689  

maybe we should just add option for the mouse user so that do not apply touch-related js patch? @laplamgor
